CREATE TABLE IF NOT EXISTS software_versions (
  version VARCHAR(40) NOT NULL PRIMARY KEY,
  released_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
